version: '3.4'

services:
  fibonacci.rabbitmq:
    # login guest:guest
    image: rabbitmq:3-management

  fibonacci.secondapp:
    image: ${DOCKER_REGISTRY-}fibonaccisecondapp
    build:
      context: .
      dockerfile: Fibonacci.SecondApp/Dockerfile
    depends_on:
      - fibonacci.rabbitmq

  fibonacci.firstapp:
    image: ${DOCKER_REGISTRY-}fibonaccifirstapp
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Fibonacci.FirstApp/Dockerfile
    depends_on:
      - fibonacci.rabbitmq
      - fibonacci.secondapp
